### ISSUE TITLE
Source : La loi n°84-09 

### ISSUE THREAD

**Issue by Reddine** [mohsenuss91/AlgerianAdministrativeDivision#13]
la version arabe: http://www.interieur.gov.dz/PublishingFiles/loi.84-09_ar.pdf
la version française: http://www.interieur.gov.dz/PublishingFiles/loi.84-09_fr.pdf
 
P.S: Selon la version arabe, la commune Sidi Amar c'est سيدي عامر ! nice to know that :D

**Comment by mohsenuss91** [comment]
Thank you @Reddine  :+1:
