### ISSUE TITLE
structure is inconsitent

### ISSUE THREAD

**Issue by bensialih** [mohsenuss91/AlgerianAdministrativeDivision#23]
Salam Alaikum,

Can we have a stricter structure. I'm just parsing data and I've noticed that not all wilayat have data missing.

There is missing data like french, arabic, and baladiyas. Some things mean that the structure has inconsistencies.

Please see images attached

Kind regards,
Abdel Hakim
![Screenshot from 2019-08-26 00-06-27](https://user-images.githubusercontent.com/14818716/63657160-2158cb80-c796-11e9-84f7-978fc23dde6d.png)
![Screenshot from 2019-08-26 00-05-43](https://user-images.githubusercontent.com/14818716/63657163-261d7f80-c796-11e9-8957-01a3eecb4696.png)

**Comment by bensialih** [comment]
fixed

**Comment by mohsenuss91** [comment]
@bensialih Thank you!
