### ISSUE TITLE
empty datasets

### ISSUE THREAD

**Issue by bensialih** [mohsenuss91/AlgerianAdministrativeDivision#25]
Salam,

The data may need cleaning.
Some data is empty.

![Screenshot from 2019-08-26 10-57-32](https://user-images.githubusercontent.com/14818716/63682713-6e698b80-c7f0-11e9-988b-cab0624f9613.png)

**Comment by bensialih** [comment]
fixed in json file

**Comment by mohsenuss91** [comment]
@bensialih Nice. Thank you!
